name: 'Build Docker Images'

on:
  pull_request:

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    steps:
    - name: Compute Docker Tag
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-12)" >> $GITHUB_ENV

    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Cache BYOND Environment
      run: cp paradise.dme paradise.dme.original

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Emerald
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        tags: |
          scorpiostation/scorpio:${{ env.GITHUB_SHA_SHORT }}
          scorpiostation/scorpio:${{ env.GITHUB_SHA_SHORT }}-emerald
          scorpiostation/scorpio:latest
        build-args: NANOMAP_FILE="./_maps/map_files/emerald/emerald.dmm"
        push: false

    - name: Switch to Cyberiad Map
      run: |
        cp paradise.dme.original paradise.dme
        sed -i -e "s/_maps\\\emerald.dm/_maps\\\cyberiad.dm/" paradise.dme

    - name: Build Cyberiad
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        tags: scorpiostation/scorpio:${{ env.GITHUB_SHA_SHORT }}-cyberiad
        build-args: NANOMAP_FILE="./_maps/map_files/cyberiad/cyberiad.dmm"
        push: false

    - name: Switch to Delta Map
      run: |
        cp paradise.dme.original paradise.dme
        sed -i -e "s/_maps\\\emerald.dm/_maps\\\delta.dm/" paradise.dme

    - name: Build Delta
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        tags: scorpiostation/scorpio:${{ env.GITHUB_SHA_SHORT }}-delta
        build-args: NANOMAP_FILE="./_maps/map_files/Delta/delta.dmm"
        push: false

    - name: Switch to MetaStation Map
      run: |
        cp paradise.dme.original paradise.dme
        sed -i -e "s/_maps\\\emerald.dm/_maps\\\metastation.dm/" paradise.dme

    - name: Build MetaStation
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        tags: scorpiostation/scorpio:${{ env.GITHUB_SHA_SHORT }}-metastation
        build-args: NANOMAP_FILE="./map_files/MetaStation/MetaStation.v41A.II.dmm"
        push: false
